### ISSUE TITLE
Support GKE regional cluster type

### ISSUE THREAD

**Issue by joaquindlz** [estafette/estafette-gke-node-pool-shifter#10]
Hi,

In GKE cluster version 1.10.6-gke.11 this tool doesn't work.
Deployed with Helm.

**Config**:
```
nodePool:
  # The name of the node pool to shift from
  from: "pool-1"

  # The name of the node pool to shift to
  to: "pool-2-preemptible"

  # The minimum number of node to keep for the node pool to shift
  fromMinNode: 6
```

**Log**:
```
{"time":"2018-11-25T19:13:03Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","branch":"master","revision":"4976666d587383eed14694aa00764a5c6db37aea","buildDate":"2017-09-12T15:50:30Z","goVersion":"go1.9","nodePooldFrom":"pool-1","nodePooldTo":"pool-2-preemptible","message":"Starting estafette-gke-node-pool-shifter..."}
{"time":"2018-11-25T19:13:03Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","port":":9001","path":"/metrics","message":"Serving Prometheus metrics..."}
{"time":"2018-11-25T19:13:06Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","message":"Checking node pool to shift..."}
{"time":"2018-11-25T19:13:06Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","node-pool":"pool-1","message":"Node pool has 8 node(s), minimun wanted: 6 node(s)"}
{"time":"2018-11-25T19:13:06Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","node-pool":"pool-2-preemptible","message":"Attempting to shift one node..."}
{"time":"2018-11-25T19:13:06Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","node-pool":"pool-2-preemptible","message":"Adding 1 node to the pool, currently 0 node(s), expecting 1 node(s)"}
{"time":"2018-11-25T19:13:06Z","severity":"error","app":"estafette-gke-node-pool-shifter","version":"1.0.11","error":"googleapi: Error 404: Not found: projects/[my-project-name]/zones/us-central1-b/clusters/[my-cluster-name]., notFound","node-pool":"pool-2-preemptible","message":"Error resizing node pool"}
```
